# -*- coding: utf-8 -*-
"""of Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2171LrPjKbHik6c2ArGv3W4l-mp98st

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** Rizky w
- **Email:** ticctocc28@gmail.com
- **ID Dicoding:** rizky_w_chpq

## Menentukan Pertanyaan Bisnis

- **Bagaimana pengaruh faktor cuaca terhadap jumlah penyewaan sepeda per hari?**

  - **Tujuan**: Memahami bagaimana kondisi cuaca tertentu (seperti clear, mist, atau light snow/rain) memengaruhi tingkat penyewaan sepeda.

- **Apakah terdapat pola musiman yang signifikan dalam jumlah penyewaan sepeda, dan bagaimana pola ini dapat memengaruhi strategi pengelolaan sistem?**

 - **Tujuan**: Mengidentifikasi fluktuasi penyewaan sepeda berdasarkan musim (spring, summer, fall, winter).

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

hour_data = pd.read_csv('dashboard/hour.csv')
day_data = pd.read_csv('dashboard/day.csv')

# Streamlit Dashboard
st.title("Dashboard Analisis Penyewaan Sepeda")

# Sidebar
st.sidebar.header("Filter Data")
season = st.sidebar.multiselect(
    "Pilih Musim:", options=day_data['season'].unique(),
    default=day_data['season'].unique()
)

weather = st.sidebar.multiselect(
    "Pilih Kondisi Cuaca:", options=day_data['weathersit'].unique(),
    default=day_data['weathersit'].unique()
)

# Filter data berdasarkan input
filtered_data = day_data[
    (day_data['season'].isin(season)) &
    (day_data['weathersit'].isin(weather))
]

# Visualization 1: Pengaruh cuaca
st.subheader("Pengaruh Cuaca terhadap Penyewaan")
fig_weather = plt.figure(figsize=(10, 6))
sns.boxplot(data=filtered_data, x='weathersit', y='cnt', palette='Set2')
plt.title("Impact of Weather on Daily Bike Rentals")
plt.xlabel("Weather Situation (1: Clear, 2: Mist, 3: Light Snow/Rain)")
plt.ylabel("Total Daily Rentals")
st.pyplot(fig_weather)

# Visualization 2: Pola musiman
st.subheader("Pola Musiman dalam Penyewaan")
fig_season = plt.figure(figsize=(10, 6))
sns.boxplot(data=filtered_data, x='season', y='cnt', palette='coolwarm')
plt.title("Seasonal Patterns in Daily Bike Rentals")
plt.xlabel("Season (1: Spring, 2: Summer, 3: Fall, 4: Winter)")
plt.ylabel("Total Daily Rentals")
st.pyplot(fig_season)

st.write("Dashboard ini menampilkan hasil analisis penyewaan sepeda berdasarkan cuaca dan musim.")